// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFFHM1az2pGONDlreFu2FrxmNIGE4I96s',
    appId: '1:311189801730:web:9708e8f1ef7a891eb1501b',
    messagingSenderId: '311189801730',
    projectId: 'shadowing-app-dev',
    authDomain: 'shadowing-app-dev.firebaseapp.com',
    storageBucket: 'shadowing-app-dev.firebasestorage.app',
    measurementId: 'G-TJL6V7N0FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW3AKO-egcIBX5rrZcJg03kGiQ0dm-VcM',
    appId: '1:311189801730:android:be64f90106f66686b1501b',
    messagingSenderId: '311189801730',
    projectId: 'shadowing-app-dev',
    storageBucket: 'shadowing-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZX59tDmEnS-FkvX9ymVhewk6AXfJtXGU',
    appId: '1:311189801730:ios:a4fefbe6b899c5adb1501b',
    messagingSenderId: '311189801730',
    projectId: 'shadowing-app-dev',
    storageBucket: 'shadowing-app-dev.firebasestorage.app',
    iosClientId: '311189801730-tmsfsph64htbahlp7ldtrenstkbk0cfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shadowingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZX59tDmEnS-FkvX9ymVhewk6AXfJtXGU',
    appId: '1:311189801730:ios:a4fefbe6b899c5adb1501b',
    messagingSenderId: '311189801730',
    projectId: 'shadowing-app-dev',
    storageBucket: 'shadowing-app-dev.firebasestorage.app',
    iosClientId: '311189801730-tmsfsph64htbahlp7ldtrenstkbk0cfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shadowingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFFHM1az2pGONDlreFu2FrxmNIGE4I96s',
    appId: '1:311189801730:web:9ae3399231bfa8e6b1501b',
    messagingSenderId: '311189801730',
    projectId: 'shadowing-app-dev',
    authDomain: 'shadowing-app-dev.firebaseapp.com',
    storageBucket: 'shadowing-app-dev.firebasestorage.app',
    measurementId: 'G-8N3X5E61J6',
  );
}
